/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import modelo.Usuarios;

/**
 *
 * @author Danniela Renderos
 */
public class Menu extends javax.swing.JFrame {

    Usuarios jugador;

    /**
     * Creates new form login
     */
    public Menu(Usuarios jugador) {
        this.jugador = jugador;
        initComponents();
        setSize(550, 300);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        conti = new javax.swing.JButton();
        top = new javax.swing.JButton();
        help = new javax.swing.JButton();
        textoLeks = new javax.swing.JLabel();
        textoUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/JJ.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 10, 350, 80);

        conti.setText("Continue");
        conti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contiActionPerformed(evt);
            }
        });
        getContentPane().add(conti);
        conti.setBounds(90, 210, 90, 23);

        top.setText("Top 10");
        top.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topActionPerformed(evt);
            }
        });
        getContentPane().add(top);
        top.setBounds(220, 210, 90, 23);

        help.setText("Help");
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });
        getContentPane().add(help);
        help.setBounds(350, 210, 80, 23);

        textoLeks.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        textoLeks.setForeground(new java.awt.Color(255, 255, 255));
        textoLeks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoLeks.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(textoLeks);
        textoLeks.setBounds(150, 130, 220, 30);
        textoLeks.setText("Lek disponibles: "+jugador.getLeks());

        textoUsuario.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        textoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        textoUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(textoUsuario);
        textoUsuario.setBounds(150, 90, 220, 30);
        textoUsuario.setText("Astronauta: "+jugador.getUsuario());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/o.gif"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -30, 850, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contiActionPerformed
        setVisible(false);
        new Lore(jugador).setVisible(true);

    }//GEN-LAST:event_contiActionPerformed

    private void topActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topActionPerformed
        setVisible(false);
        new TopTen(jugador).setVisible(true);
    }//GEN-LAST:event_topActionPerformed

    private void helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpActionPerformed
        new Ayuda(jugador).setVisible(true);
    }//GEN-LAST:event_helpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Menu().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton conti;
    private javax.swing.JButton help;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel textoLeks;
    private javax.swing.JLabel textoUsuario;
    private javax.swing.JButton top;
    // End of variables declaration//GEN-END:variables
}
