/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import dao.UsuariosDao;
import java.awt.Color;
import java.util.ArrayList;
import modelo.Usuarios;

/**
 *
 * @author Cesar Rosales <00060917@uca.edu.sv>
 */
public class TopTen extends javax.swing.JFrame {
    Usuarios jugador;
    UsuariosDao dao= new UsuariosDao();
    ArrayList<Usuarios> arrayUsuariosTop10= new ArrayList<Usuarios>();
    /**
     * Creates new form TopTen
     */
    
    public TopTen(Usuarios u) {
        this.jugador=u;
        arrayUsuariosTop10= dao.readTop10();
        initComponents();
        setSize(550,550);
        scroll.setOpaque(false);
        scroll.getViewport().setOpaque(false);
        scroll.setBorder(null);
        scroll.setViewportBorder(null);
        
        area.setBorder(null);
        area.setBackground(new Color(0,0,0,100));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroll = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        IrMenu = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        area.setEditable(false);
        area.setColumns(20);
        area.setForeground(new java.awt.Color(255, 255, 255));
        area.setRows(5);
        area.setToolTipText("");
        area.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        scroll.setViewportView(area);
        String total="";
        for(Usuarios u: arrayUsuariosTop10){
            total+=u.mostrarTop10();
        }
        area.setText(total);

        getContentPane().add(scroll);
        scroll.setBounds(70, 130, 400, 270);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/JJJ.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 20, 360, 100);

        IrMenu.setText("MENÚ");
        IrMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IrMenuActionPerformed(evt);
            }
        });
        getContentPane().add(IrMenu);
        IrMenu.setBounds(220, 440, 61, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/top.gif"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 550, 530);
        jLabel1.setText("1\n   1\n 3\n ");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IrMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IrMenuActionPerformed
       setVisible(false);
       new Menu(jugador).setVisible(true);

    }//GEN-LAST:event_IrMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TopTen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TopTen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TopTen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TopTen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TopTen().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton IrMenu;
    private javax.swing.JTextArea area;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables

}